//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsForRent
    {
        public string CarNumber { get; set; }
        public int TypeID { get; set; }
        public long Mileage { get; set; }
        public string Proper { get; set; }
        public string Available { get; set; }
        public int BranchID { get; set; }
    }
}
