//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarType
    {
        public int TypeID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public decimal CostPerDay { get; set; }
        public decimal CostPerDayDelay { get; set; }
        public string Year { get; set; }
        public string Gear { get; set; }
        public string Image { get; set; }
    }
}
